### ISSUE TITLE
"当前版本为最新版"这个弹窗，每次运行都会要点一下，能不能做成超时自动关闭的窗体

### ISSUE THREAD

**Issue by jiangpan** [JiuLing-zhang/JiuLing.AutoUpgrade#2]
**问题描述：**
"当前版本为最新版"这个弹窗，每次运行都会要点一下，能不能做成超时自动关闭的窗体

**在什么场景下会用到这个功能：**
每次都需要点击一下

**你理想的解决方案是什么：**
做成超时自动关闭的窗体

**其它：**
暂无

**Comment by JiuLing-zhang** [comment]
你是程序运行时自动检测更新吗？这种情况可以启用后台自动更新，此时当有新版本时才会提示。

```c#
    app.SetUpgrade(config =>
    {
        config.IsBackgroundCheck = true;
    });
```

**Comment by jiangpan** [comment]
我好像没有加这个，感谢大佬提醒！
