### ISSUE TITLE
支持差分更新吗

### ISSUE THREAD

**Issue by JiaoZaiShiJie** [JiuLing-zhang/JiuLing.AutoUpgrade#3]
### 功能描述

差异对比 dll更新 ,MD5验证更新

### 解决方案

支持dll对比差异更新

**Comment by JiuLing-zhang** [comment]
更新方式是解压更新包的内容，然后全覆盖替换。所以如果需要差分更新，只需要把差分部分打包后发布即可。更新包支持 md5 和 sha1 两种校验方式

**Comment by JiaoZaiShiJie** [comment]
那可不可以界面自定义;  只保留函数方法就可以了

**Comment by JiuLing-zhang** [comment]
> 那可不可以界面自定义; 只保留函数方法就可以了

不支持界面自定义
